fig1=figure; fig2=figure;
%------------------------------------%
figure(fig1)
sgtitle('Registro en el dominio del tiempo')
subplot(3,4,1)
plot(t,EEGSegments(:,1))
xlim([0 t(end)])
ylabel('Amplitud [mV]');xlabel('Tiempo [ms]')
title('1era muestra de registro')
subplot(3,4,[2 6 10])
plot(t,prom_standar_visual)
xlim([0 t(end)])
ylabel('Amplitud [mV]');xlabel('Tiempo [ms]')
title('Promediación estándar de registro')
subplot(3,4,[3 7 11])
plot(t,prom_weigthed_visual)
title('Ponderación por muestras de registro')
xlim([0 t(end)])
ylabel('Amplitud [mV]');xlabel('Tiempo [ms]')
subplot(3,4,[4 8 12])
plot(t,prom_sorted_visual)
title('Ponderación ordenada de registro')
xlim([0 t(end)])
ylabel('Amplitud [mV]');xlabel('Tiempo [ms]')
subplot(3,4,5)
plot(t,EEGSegments(:,20))
xlim([0 t(end)])
title('20va muestra de registro')
ylabel('Amplitud [mV]');xlabel('Tiempo [ms]')
subplot(3,4,9)
plot(t,EEGSegments(:,30))
xlim([0 t(end)])
title('30va muestra de registro')
ylabel('Amplitud [mV]');xlabel('Tiempo [ms]')

figure(fig2)
sgtitle('Estimadores de dispersión de los segmentos registro visual')
subplot(2,6,[1 3])
plot(segments_vector,rms_visual)
title('Estimador para ponderación por muestra (RMS)')
xlabel('Epoca');ylabel('RMS')
xlim([0 N])
subplot(2,6,[4 6])
plot(segments_vector,valor_posicion)
title('Estimador ordenado (RMS ordenado)')
xlabel('Epoca');ylabel('RMS')
xlim([0 N])

subplot(2,6,[7 8])
plot(snr_standar_prom)
title('SNR promedio clásico')
ylabel('SNR [db]'); xlabel('Epoca')
xlim([0 N])
subplot(2,6,[9 10])
plot(snr_weigthed_prom)
title('SNR promedio por pesos')
ylabel('SNR [db]'); xlabel('Epoca')
xlim([0 N])
subplot(2,6,[11 12])
plot(snr_sorted_prom)
title('SNR promedio ordenado')
ylabel('SNR [db]');xlabel('Epoca')
xlim([0 N])